services:
  app:
    build: .
    container_name: raspico-more
    tty: true
    volumes:
      - ./app/:/app
      - ./docs/:/docs
      - ../raspico-more-ext/:/raspico-more-ext
      - ../xcx-example/:/xcx-example
      - ../scratch-vm/:/scratch-vm
    # ports:
    #   - "5173:5173" # development server
